[screen]
title = "LCARS FEATURE DEMO"

[[panels]]
id = "system-status"
title = "SYSTEM STATUS"
orientation = { horizontal = "left", vertical = "bottom" }
sizing = "auto"

[[panels.views]]
id = "ovr"
name = "OVR"

[[panels.views]]
id = "grf"
name = "GRF"

[[panels.views]]
id = "dtl"
name = "DTL"

[[panels]]
id = "operations"
title = "OPERATIONS"
orientation = { horizontal = "left", vertical = "top" }
sizing = "auto"

[[panels.views]]
id = "sts"
name = "STS"

[[panels.views]]
id = "log"
name = "LOG"
